sudo: required
dist: trusty

before_install:
  # g++6
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test

  # Qt5
  - sudo apt-add-repository --yes ppa:beineri/opt-qt542-trusty
  - sudo apt-get -qq update

install:
  # g++6

  # Qt5
  - sudo apt-get update
  - sudo apt-get install qt54base qt54imageformats libqt5webkit5-dev qt54svg qtdeclarative5-dev


env: CXX="g++-6" CXXFLAGS="-std=c++11 -Wall -Wno-error"

before_script:
    - QTDIR="/opt/qt54"
    - PATH="$QTDIR/bin:$PATH"

script:
  - qmake --version
  - qmake ugene.pro CONFIG+=x64 UGENE_EXCLUDE_LIST_ENABLED=1 UGENE_USE_BUNDLED_ZLIB=0
  - make -j 3 | sed -n 'p;n;n;n;n;'
