sudo: required
dist: trusty

before_install:
  - sudo add-apt-repository ppa:beineri/opt-qt541 -y

install:
  - sudo apt-get install qtbase5-dev qtdeclarative5-dev libqt5webkit5-dev qt5-qmake libsqlite3-dev libqt5svg5-dev
  - sudo apt-get install qt5-default qttools5-dev-tools qtscript5-dev
  - sudo apt-get install libxtst-dev
  - export QMAKE=/usr/lib/x86_64-linux-gnu/qt5/bin/qmake

script:
  - qmake --version
  - qmake ugene.pro CONFIG+=x64 UGENE_EXCLUDE_LIST_ENABLED=1 UGENE_USE_BUNDLED_ZLIB=0
  - make -j 3 | sed -n 'p;n;n;n;n;'
